name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js@20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install

    - name: Lint
      run: pnpm run lint

    - name: Type check
      run: pnpm run typecheck

    - name: Build
      run: pnpm run build

    - name: Test
      run: pnpm run test

    - name: Publish
      if: github.ref == 'refs/heads/main'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: pnpx semantic-release